package io.substrait.spark

import io.substrait.plan.ProtoPlanConverter
import io.substrait.spark.logical.ToLogicalPlan
import org.apache.hadoop.shaded.com.google.gson.{Gson, JsonObject}
import org.apache.spark.SparkFunSuite
import org.apache.spark.sql.SparkSession
import org.apache.spark.sql.catalyst.analysis.TableAlreadyExistsException
import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan

import java.io.IOException
import java.nio.file.{Files, Path, Paths}

/**
 * Contains test cases for the Substrait to Spark converter where the substrait plan is generated
 * by a (trusted) third party tool. This deviates from the 'round-trip' methodology whereby
 * all the substrait plans are generated by the Spark to Substrait converter in this repo.
 *
 * The Substrait plan is loaded from a proto file (JSON format).
 */
class SubstraitJsonSuite extends SparkFunSuite {
  var spark: SparkSession =
    SparkSession.builder().config("spark.master", "local").enableHiveSupport().getOrCreate()

  test("Aggregate") {
    val substraitPlanPath = Path.of("../src/test/resources/substrait_plan_with_aggregate_op.json")
    val defaultSchema = "test1"

    // Create table test1.vehicles
    val vehiclesFile = "../src/test/resources/vehicles_subset_2023.csv"
    val dsVehicles = spark.read.option("header", true).option("inferSchema", true).csv(Paths.get(vehiclesFile).toAbsolutePath.toString)
    spark.sql("CREATE NAMESPACE IF NOT EXISTS test1")
    spark.sql("DROP TABLE IF EXISTS test1.vehicles")
    try dsVehicles.writeTo("test1.vehicles").create()
    catch {
      case _: TableAlreadyExistsException =>
      // Table already exists, ignore
    }

    // Create table test1.tests
    val testsFile = "../src/test/resources/tests_subset_2023.csv"
    val dsTests = spark.read.option("header", true).option("inferSchema", true).csv(Paths.get(testsFile).toAbsolutePath.toString)
    spark.sql("DROP TABLE IF EXISTS test1.tests")
    try dsTests.writeTo("test1.tests").create()
    catch {
      case _: TableAlreadyExistsException =>
      // Table already exists, ignore
    }

    val sparkPlan = toSpark(substraitPlanPath, defaultSchema)
    val output = spark.sessionState.executePlan(sparkPlan).executedPlan.execute()
    // there should be 25 rows and 3 columns
    assertResult(25)(output.count())
    assertResult(3)(output.take(1)(0).numFields)
  }

  test("nba") {
    val substraitPlanPath = Path.of("../src/test/resources/substrait_plan_nba_california.json")
    val defaultSchema = "nba"

    // Create table nba.team
    val vehiclesFile = "../src/test/resources/nba_team.csv"
    val dsVehicles = spark.read.option("header", true).option("inferSchema", true).csv(Paths.get(vehiclesFile).toAbsolutePath.toString)
    spark.sql("CREATE NAMESPACE IF NOT EXISTS nba")
    spark.sql("DROP TABLE IF EXISTS nba.team")
    try dsVehicles.writeTo("nba.team").create()
    catch {
      case _: TableAlreadyExistsException =>
      // Table already exists, ignore
    }

    // Create table nba.team_history
    val testsFile = "../src/test/resources/nba_team_history.csv"
    val dsTests = spark.read.option("header", true).option("inferSchema", true).csv(Paths.get(testsFile).toAbsolutePath.toString)
    spark.sql("DROP TABLE IF EXISTS nba.team_history")
    try dsTests.writeTo("nba.team_history").create()
    catch {
      case _: TableAlreadyExistsException =>
      // Table already exists, ignore
    }

    val sparkPlan = toSpark(substraitPlanPath, defaultSchema)
    val output = spark.sessionState.executePlan(sparkPlan).executedPlan.execute()
    // there should be 13 rows and 21 columns
    assertResult(13)(output.count())
    assertResult(21)(output.take(1)(0).numFields)
  }

  @throws[IOException]
  def toSpark(substraitPlanPath: Path, defaultSchema: String): LogicalPlan = {
    val defaultCatalog = "spark_catalog"
    val jsonContent = Files.readString(substraitPlanPath)
    val gson = new Gson
    val jsonObj = gson.fromJson(jsonContent, classOf[JsonObject])
    val builder = io.substrait.proto.Plan.newBuilder
    com.google.protobuf.util.JsonFormat.parser.ignoringUnknownFields.merge(jsonObj.toString, builder)
    val proto = builder.build
    val protoToPlan = new ProtoPlanConverter
    val plan = protoToPlan.from(proto)
    spark.catalog.setCurrentCatalog(defaultCatalog)
    spark.catalog.setCurrentDatabase(defaultSchema)
    val substraitConverter = new ToLogicalPlan(spark)
    substraitConverter.convert(plan)
  }

}
