/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
  id("java")
  id("com.diffplug.spotless") version "6.19.0"
}

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

val JUNIT_VERSION = properties.get("junit.version")
val SLF4J_VERSION = properties.get("slf4j.version")

dependencies {
  implementation(projects.core)
  implementation(projects.isthmus)
  runtimeOnly("org.slf4j:slf4j-jdk14:${SLF4J_VERSION}")
  testImplementation("org.junit.jupiter:junit-jupiter:${JUNIT_VERSION}")
}

// testing {
//     suites {
//         // Configure the built-in test suite
//         test {
//             // Use JUnit Jupiter test framework
//             useJUnitJupiter('5.11.1')
//         }
//     }
// }

java {
  toolchain { languageVersion.set(JavaLanguageVersion.of(17)) }
}

// application {
//     // Define the main class for the application.
//     mainClass = 'org.example.App'
// }
