/*
 * This source file was generated by the Gradle 'init' task
 */
package io.substrait.examples;

import io.substrait.extension.SimpleExtension;
import io.substrait.isthmus.SubstraitToCalcite;
import io.substrait.isthmus.SubstraitToSql;
import io.substrait.isthmus.SubstraitTypeSystem;
import io.substrait.plan.ProtoPlanConverter;
import io.substrait.proto.Plan;
import java.util.Base64;
import org.apache.calcite.jdbc.JavaTypeFactoryImpl;
import org.junit.jupiter.api.Test;

import com.google.protobuf.InvalidProtocolBufferException;

class IsthmusApiTest {

  /** Arbitary Substrait plan encoded as base 64 */
  public static final String base64Plan = "ChsIAhIXL2Z1bmN0aW9uc19ib29sZWFuLnlhbWwKHggBEhovZnVuY3Rpb25zX2NvbXBhcmlzb24ueWFtbBITGhEIARoNZXF1YWw6YW55X2FueRIQGg4IAhABGghhbmQ6Ym9vbBISGhAIARACGgpsdDphbnlfYW55GtwGEtkGCqUFOqIFChMSEQoPDxAREhMUFRYXGBkaGxwdEtgDEtUDCgIKABLtAjLqAgoCCgASkgEKjwEKAgoAEn0KCnZlaGljbGVfaWQKBG1ha2UKBW1vZGVsCgZjb2xvdXIKCWZ1ZWxfdHlwZQoRY3lsaW5kZXJfY2FwYWNpdHkKDmZpcnN0X3VzZV9kYXRlEiwKBCoCEAIKBGICEAEKBGICEAEKBGICEAEKBGICEAEKBCoCEAIKBGICEAEYAjoKCgh2ZWhpY2xlcxqoAQqlAQoCCgASlQEKB3Rlc3RfaWQKCnZlaGljbGVfaWQKCXRlc3RfZGF0ZQoJdGVzdF90eXBlCgp0ZXN0X2NsYXNzCgt0ZXN0X3Jlc3VsdAoMdGVzdF9taWxlYWdlCg1wb3N0Y29kZV9hcmVhEjIKBCoCEAIKBCoCEAIKBGICEAEKBGICEAEKBGICEAEKBGICEAEKBCoCEAIKBGICEAEYAjoHCgV0ZXN0cyIiGiAaBAoCEAIiChoIEgYKAhIAIgAiDBoKEggKBBICCAgiADABGl8aXQgBGgQKAhABIi0aKxopGgQKAhABIhgaFloUCgRiAhABEgoSCAoEEgIIDCIAGAIiBxoFCgNiAUYiJBoiGiAIAhoECgIQAiIMGgoSCAoEEgIIDSIAIggaBgoEKPCiBBoIEgYKAhIAIgAaChIICgQSAggBIgAaChIICgQSAggCIgAaChIICgQSAggDIgAaChIICgQSAggEIgAaChIICgQSAggFIgAaChIICgQSAggGIgAaChIICgQSAggHIgAaChIICgQSAggIIgAaChIICgQSAggJIgAaChIICgQSAggKIgAaChIICgQSAggLIgAaChIICgQSAggMIgAaChIICgQSAggNIgAaChIICgQSAggOIgASCnZlaGljbGVfaWQSBG1ha2USBW1vZGVsEgZjb2xvdXISCWZ1ZWxfdHlwZRIRY3lsaW5kZXJfY2FwYWNpdHkSDmZpcnN0X3VzZV9kYXRlEgd0ZXN0X2lkEgt2ZWhpY2xlX2lkMBIJdGVzdF9kYXRlEgl0ZXN0X3R5cGUSCnRlc3RfY2xhc3MSC3Rlc3RfcmVzdWx0Egx0ZXN0X21pbGVhZ2USDXBvc3Rjb2RlX2FyZWE=";

  @Test
  void substraitToSqlviaCalcite() {

    /** Excplitily convert via calcite to sql */
    try {

      Plan protoPlan = Plan.parseFrom(Base64.getDecoder().decode(base64Plan));

      ProtoPlanConverter converter = new io.substrait.plan.ProtoPlanConverter();
      io.substrait.plan.Plan pojoPlan = converter.from(protoPlan);

      System.out.println("POJO Substrait Plan::\n" + pojoPlan);

      SimpleExtension.ExtensionCollection extensions = SimpleExtension.loadDefaults();

      SubstraitToCalcite substrait2Calcite = new SubstraitToCalcite(
          extensions, new JavaTypeFactoryImpl(SubstraitTypeSystem.TYPE_SYSTEM));

      for (var root : pojoPlan.getRoots()) {
        var calciteRel = substrait2Calcite.convert(root).project();
        String sql = SubstraitToSql.toSql(calciteRel);
        System.out.println(sql);
      }

    } catch (InvalidProtocolBufferException e) {
      e.printStackTrace();
    }
  }

  @Test
  void substraitToSql() {

    /** Excplitily convert via calcite to sql */
    try {

      Plan protoPlan = Plan.parseFrom(Base64.getDecoder().decode(base64Plan));

      ProtoPlanConverter converter = new io.substrait.plan.ProtoPlanConverter();
      io.substrait.plan.Plan pojoPlan = converter.from(protoPlan);

      System.out.println("POJO Substrait Plan::\n" + pojoPlan);

      for (String sql : SubstraitToSql.toSql(pojoPlan)) {
        System.out.println(sql);
      }

    } catch (InvalidProtocolBufferException e) {
      e.printStackTrace();
    }
  }
}
