/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.substrait.extension.SimpleExtension;
import io.substrait.isthmus.SubstraitToCalcite;
import io.substrait.isthmus.SubstraitToSql;
import io.substrait.isthmus.SubstraitTypeSystem;
import io.substrait.proto.Plan;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.apache.calcite.avatica.util.Base64;
import org.apache.calcite.jdbc.JavaTypeFactoryImpl;

public class App {

  /** Arbitary Substrait plan encoded as base 64 */
  public static final String base64Plan =
      "ChsIAhIXL2Z1bmN0aW9uc19ib29sZWFuLnlhbWwKHggBEhovZnVuY3Rpb25zX2NvbXBhcmlzb24ueWFtbBITGhEIARoNZXF1YWw6YW55X2FueRIQGg4IAhABGghhbmQ6Ym9vbBISGhAIARACGgpsdDphbnlfYW55GtwGEtkGCqUFOqIFChMSEQoPDxAREhMUFRYXGBkaGxwdEtgDEtUDCgIKABLtAjLqAgoCCgASkgEKjwEKAgoAEn0KCnZlaGljbGVfaWQKBG1ha2UKBW1vZGVsCgZjb2xvdXIKCWZ1ZWxfdHlwZQoRY3lsaW5kZXJfY2FwYWNpdHkKDmZpcnN0X3VzZV9kYXRlEiwKBCoCEAIKBGICEAEKBGICEAEKBGICEAEKBGICEAEKBCoCEAIKBGICEAEYAjoKCgh2ZWhpY2xlcxqoAQqlAQoCCgASlQEKB3Rlc3RfaWQKCnZlaGljbGVfaWQKCXRlc3RfZGF0ZQoJdGVzdF90eXBlCgp0ZXN0X2NsYXNzCgt0ZXN0X3Jlc3VsdAoMdGVzdF9taWxlYWdlCg1wb3N0Y29kZV9hcmVhEjIKBCoCEAIKBCoCEAIKBGICEAEKBGICEAEKBGICEAEKBGICEAEKBCoCEAIKBGICEAEYAjoHCgV0ZXN0cyIiGiAaBAoCEAIiChoIEgYKAhIAIgAiDBoKEggKBBICCAgiADABGl8aXQgBGgQKAhABIi0aKxopGgQKAhABIhgaFloUCgRiAhABEgoSCAoEEgIIDCIAGAIiBxoFCgNiAUYiJBoiGiAIAhoECgIQAiIMGgoSCAoEEgIIDSIAIggaBgoEKPCiBBoIEgYKAhIAIgAaChIICgQSAggBIgAaChIICgQSAggCIgAaChIICgQSAggDIgAaChIICgQSAggEIgAaChIICgQSAggFIgAaChIICgQSAggGIgAaChIICgQSAggHIgAaChIICgQSAggIIgAaChIICgQSAggJIgAaChIICgQSAggKIgAaChIICgQSAggLIgAaChIICgQSAggMIgAaChIICgQSAggNIgAaChIICgQSAggOIgASCnZlaGljbGVfaWQSBG1ha2USBW1vZGVsEgZjb2xvdXISCWZ1ZWxfdHlwZRIRY3lsaW5kZXJfY2FwYWNpdHkSDmZpcnN0X3VzZV9kYXRlEgd0ZXN0X2lkEgt2ZWhpY2xlX2lkMBIJdGVzdF9kYXRlEgl0ZXN0X3R5cGUSCnRlc3RfY2xhc3MSC3Rlc3RfcmVzdWx0Egx0ZXN0X21pbGVhZ2USDXBvc3Rjb2RlX2FyZWE=";

  public static void main(String[] args) {
    var app = new App();

    app.substraitToSql().forEach(System.out::println);
  }

  public List<String> substraitToSql() {

    List<String> sql = new ArrayList<>();
    try {
      Plan protoPlan = Plan.parseFrom(Base64.decode(base64Plan));

      var converter = new io.substrait.plan.ProtoPlanConverter();
      io.substrait.plan.Plan pojoPlan = converter.from(protoPlan);

      System.out.println("POJO Substrait Plan::\n" + pojoPlan);
      SimpleExtension.ExtensionCollection extensions = SimpleExtension.loadDefaults();
      var substrait2Calcite =
          new SubstraitToCalcite(
              extensions, new JavaTypeFactoryImpl(SubstraitTypeSystem.TYPE_SYSTEM));

      for (var root : pojoPlan.getRoots()) {
        var calciteRel = substrait2Calcite.convert(root).project();
        sql.add(SubstraitToSql.toSql(calciteRel));
      }

    } catch (IOException e) {
      e.printStackTrace(System.out);
    }
    return sql;
  }
}
