name: Sanity Check Environment

on:
  workflow_dispatch:

jobs:
  sanity_check:
    name: Sanity Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Validate credentials for Sonatype and Signing
        run: ./ci/release/sanity.sh
        env:
          MAVENCENTRAL_USERNAME: ${{ secrets.M2_CENTRAL_USERNAME }}
          MAVENCENTRAL_PASSWORD: ${{ secrets.M2_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.M2_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.M2_SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.M2_SIGNING_KEY }}
